### ISSUE TITLE
Front-End

### ISSUE THREAD

**Issue by ChristieThammavongRevature** [08162021-dotnet-uta/P2_CafeAPI#3]

**Comment by KyleHillRevature** [comment]
Make the issue more narrow. The idea is that you will create a branch from main for a specific piece of functionality. A good one for right now would be "Create search bar, submit query, display API results".

**Comment by ChristieThammavongRevature** [comment]
Ahh, okay. Gotcha. Should I delete the Front-End branch I made earlier?

**Comment by KyleHillRevature** [comment]
I believe you can rename it. Not sure on the git syntax though.

**Comment by ChristieThammavongRevature** [comment]
Okay, I'll leave it as is for now and rename it later. I plan on completing the Angular tutorial tonight so hopefully I'll have a good idea on where to start
